### ISSUE TITLE
terraform validate reports api_key as required

### ISSUE THREAD

**Issue by hollow** [tailscale/terraform-provider-tailscale#132]
`terraform validate` reports `api_key` as missing from provider config when using `TAILSCALE_API_KEY` from the environment (or in Terraform Cloud):

```
Error: Missing required argument

  on tailscale.tf line 1, in provider "tailscale":
   1: provider "tailscale" {

The argument "api_key" is required, but no definition was found.
```

Not sure how other providers handle this to make the validation happy, but my best guess is that it should not be marked as required and fail at runtime when no valid API key has been configured.

**Comment by davidsbond** [comment]
Hi @hollow, thanks for raising this.

I believe the problem is based on the provider setup [here](https://github.com/davidsbond/terraform-provider-tailscale/blob/master/tailscale/provider.go#L25). I've double checked the documentation for the `Required` field and it states:

> Required cannot be used with Computed, Default, DefaultFunc, DiffSuppressFunc, DiffSuppressOnRefresh, InputDefault, Optional, or StateFunc.

The provider does indeed use both `Required` and `DefaultFunc`. The same is true for the `tailnet` argument, which will also need to change.

So I think you are correct with your best guess. I'll take a look at modifying these fields when I can unless you'd like to submit the fix yourself. Let me know if you'd like to raise the PR, contributions always welcome :) 

If you do want to make the change yourself, you can add the additional checks for blank fields [here](https://github.com/davidsbond/terraform-provider-tailscale/blob/master/tailscale/provider.go#L70)

**Comment by hollow** [comment]
Hey @davidsbond, thanks for the quick reply!

I might take a look at this in a bit since it makes my pre-commit hook fail now and it cannot be ignored easily. I'll send a PR your way then 🙌

**Comment by xcskier56** [comment]
Hi @davidsbond, first off, thanks for making a Tailscale provider! Second, I think this issue is not fixed, or something else is going on b/c I'm still running into this problem on `0.13.5`. See my logs:

`terraform providers`
![Screen Shot 2022-09-17 at 10 11 23 AM](https://user-images.githubusercontent.com/2357871/190863815-6737bd69-5619-4d0e-b39c-6baff15a89d7.png)

`terraform plan`
![Screen Shot 2022-09-17 at 10 12 01 AM](https://user-images.githubusercontent.com/2357871/190863836-c46f29ea-1f35-4ce8-bab9-17c28a45fd92.png)

```terraform
terraform {
  backend "s3" {
    region = "us-east-1"
    bucket = "<my_bucket>"
    key    = "<key>"
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.27"
    }
    tailscale = {
      source  = "tailscale/tailscale"
      version = "0.13.5"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

provider "tailscale" {
  tailnet = "<my tailnet>"
}
```

Thanks

**Comment by davidsbond** [comment]
Hey @xcskier56, sorry to hear about your issue. That error is raised here:

https://github.com/tailscale/terraform-provider-tailscale/blob/6eabefbcecba4617809e101d578e68ffa6f3d01a/tailscale/provider.go#L73

Which suggests that you don't have the `TAILSCALE_API_KEY` environment variable set. Can you confirm that?

**Comment by xcskier56** [comment]
Yep! It is set... with a typo in it 🤦 it's working now. Thanks

![homer-dissapper](https://user-images.githubusercontent.com/2357871/190865082-627e65e0-42c6-42da-81ff-7bfb8e638c77.gif)

**Comment by davidsbond** [comment]
Happens to the bset of us
